services:
  server:
    image: crpi-266p90eq4h6brayr.cn-hangzhou.personal.cr.aliyuncs.com/1yie/dockerbase:server-latest
    container_name: ichiyo-server
    volumes:
      - ./data:/app/server/data
    environment:
      - DATABASE_URL=file:/app/server/data/sqlite.db
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: always

  web:
    image: crpi-266p90eq4h6brayr.cn-hangzhou.personal.cr.aliyuncs.com/1yie/dockerbase:web-latest
    container_name: ichiyo-web
    ports:
      - '3000:80'
    depends_on:
      - server
    restart: always
